#!/bin/sh
# स्वामित्वम् (C) 2015-2020, Infopercept Consulting.
# निर्मितम् Infopercept Consulting द्वारा <info@infopercept.com>.
# Infopercept Consulting सम्पत्तिः
# अयं कार्यक्रमः मुक्तसॉफ्टवेयरम् अस्ति; भवान् एतत् पुनर्वितरणं परिवर्तनं वा कर्तुं शक्नोति GPLv2 नियमानुसारम्

WPYTHON_BIN="framework/python/bin/python3"

SCRIPT_PATH_NAME="$0"

DIR_NAME="$(cd $(dirname ${SCRIPT_PATH_NAME}); pwd -P)"
SCRIPT_NAME="$(basename ${SCRIPT_PATH_NAME})"

case ${DIR_NAME} in
    */active-response/bin | */wodles*)
        if [ -z "${SIEM_PATH}" ]; then
            SIEM_PATH="$(cd ${DIR_NAME}/../..; pwd)"
        fi

	PYTHON_SCRIPT="${DIR_NAME}/${SCRIPT_NAME}.py"
    ;;
    */bin)
	if [ -z "${SIEM_PATH}" ]; then
            SIEM_PATH="$(cd ${DIR_NAME}/..; pwd)"
        fi

	PYTHON_SCRIPT="${SIEM_PATH}/framework/scripts/${SCRIPT_NAME}.py"
    ;;
     */integrations)
        if [ -z "${SIEM_PATH}" ]; then
            SIEM_PATH="$(cd ${DIR_NAME}/..; pwd)"
        fi

	PYTHON_SCRIPT="${DIR_NAME}/${SCRIPT_NAME}.py"
    ;;
esac


${SIEM_PATH}/${WPYTHON_BIN} ${PYTHON_SCRIPT} $@